version: 2.1
orbs:
  node: circleci/node@1.1.6

executors:
  app-executor:
    docker:
        - image: circleci/node:15.5.0
    working_directory: ~/repo

aliases:
  - &show-current-branch-name
    run:
      name: Show current branch
      command: echo ${CIRCLE_BRANCH}
  - &restore-cache
    restore_cache:
      keys:
        - app-{{checksum "package.json"}}
        - app-
  - &install-dependencies
    run:
      name: install dependencies
      command: npm install

  - &save-cache
    save_cache:
      paths:
        - node_modules
      key: app-{{checksum "package.json"}}

jobs:
  build:
    executor: app-executor
    steps:
      - checkout
      - *show-current-branch-name
      - *restore-cache
      - *install-dependencies
      - *save-cache
  linting:
    executor: app-executor
    steps:
      - checkout
      - *show-current-branch-name
      - *restore-cache
      - run:
          name: Run linting
          command: npm run lint
  prettier:
    executor: app-executor
    steps:
      - checkout
      - *show-current-branch-name
      - *restore-cache
      - run:
          name: Run prettier
          command: npm run prettier:check
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - *show-current-branch-name
      - *restore-cache
      - run:
          name: Run test
          command: npm test

workflows:
  build-and-tests:
    jobs:
      - build
      - linting:
          requires:
            - build
          filters:
            branches:
              only:
                - develop
                - main
      - prettier:
          requires:
            - build
          filters:
            branches:
              only:
                - develop
                - main
      - test:
          requires:
            - linting
          filters:
            branches:
              only:
                - develop
                - main